export const EXPENSE_ITEM_REQUEST = "EXPENSE_ITEM_REQUEST"
export const EXPENSE_ITEM_SUCCESS = "EXPENSE_ITEM_SUCCESS"
export const EXPENSE_ITEM_FAILED = "EXPENSE_ITEM_FAILED"

export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST"
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS"
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED"

export const UPDATE_EXPENSE_REQUEST = "UPDATE_EXPENSE_REQUEST"
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS"
export const UPDATE_EXPENSE_FAILED = "UPDATE_EXPENSE_FAILED"

export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST"
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS"
export const DELETE_EXPENSE_FAILED = "DELETE_EXPENSE_FAILED"

