export const USER_ITEM_REQUEST = "USER_ITEM_REQUEST"
export const USER_ITEM_SUCCESS = "USER_ITEM_SUCCESS"
export const USER_ITEM_FAILED = "USER_ITEM_FAILED"

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILED = "ADD_ITEM_FAILED"


export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILED = "UPDATE_ITEM_FAILED"

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST"
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED"


